name: Keep Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # roda a cada 5 minutos
  workflow_dispatch:         # permite rodar manualmente também

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        run: |
          curl -s https://dr-remo-site.onrender.com/ > /dev/null
